services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shop-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ../.env

volumes:
  rabbitmq_data: